### ISSUE TITLE
Logo Design Idea 1

### ISSUE THREAD

**Issue by chekkan** [tusklehq/tusklehq.github.io#5]
the word tuskle with a stethoscope used instead of the letter u.
The font used is Dosis Bold.
https://www.vectorstock.com/royalty-free-vector/heart-heartbeat-stethoscope-vector-10921962
Perhaps, use illustrator to get this done?

**Comment by anilkilic** [comment]
![tuskle](https://user-images.githubusercontent.com/2311397/46438762-654e7680-c767-11e8-8922-abf03985954e.png) | ![tuskle-ss](https://user-images.githubusercontent.com/2311397/46438761-64b5e000-c767-11e8-834c-a4dac3b049ee.png)
-|-

You can use this one if you like. I couldn't see any licensing information, so you can use it under cc or whatever suits your project. 

[AI & SVG](https://github.com/tusklehq/tusklehq.github.io/files/2443794/Archive.zip)

**Comment by chekkan** [comment]
This is amazing @anilkilic. Did you do this yourself? If so, thank you so much.

**Comment by chekkan** [comment]
Thanks, @anilkilic for your contribution. I will add these to the site.
